

const ProductHeader = () => {
  return (
    <div className="">
        <h1 className="bozos-header text-5xl md:text-7xl font-thin">Newest Products generated by ai</h1>
        <div className="flex flex-col lg:flex-row gap-4 lg:items-center justify-between ">
          <p className="text-xs md:text-sm text-gray-800  mt-2 md:mt-0">Shop the Latest AI Generated Ankara Styles: Stay ahead of the curve with our newest style idea.</p>
          <div className="flex flex-col mt-3 md:mt-0">
            <h2 className="font-medium tracking-wide">All Products</h2>
            <div className="h-0.5 w-12 bg-black lg:self-end" />
          </div>
        </div>
    </div>
  )
}
export default ProductHeader